
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-files
  namespace: {{ .Values.kube.namespace }}
  labels:
    {{- include "common.labels" . }}
data:
  receiver_groups.yaml: |
    receiver_groups:
      {{- range .Values.receiver_groups }}
      - name: {{ .name }}
        receivers: 
        {{- range .receivers }}
          - {{ . }}
        {{- end }}
      {{- end }}